DROP TABLE family cascade ;
DROP TABLE issue cascade ;
DROP TABLE supporter cascade ;
DROP TABLE device cascade ;
DROP TABLE sensor cascade ;
DROP TABLE room cascade ;
DROP TABLE schedule_script cascade ;
DROP TABLE condition_script cascade ;
DROP TABLE contact cascade ;
DROP TABLE list_action_script cascade ;
DROP TABLE device_action cascade ;
DROP TABLE list_script_user cascade ;
DROP TABLE script cascade ;
DROP TABLE list_user_house cascade ;
DROP TABLE list_user_family cascade ;
DROP TABLE "user" cascade ;
DROP TABLE house cascade ;
DROP TABLE address cascade ;

DROP TYPE problem_type;
DROP TYPE house_type;
DROP TYPE device_type;
DROP TYPE sensor_type;
DROP TYPE action_type;
DROP TYPE script_type;
DROP TYPE country;
DROP TYPE city;
DROP TYPE room_type;
DROP TYPE gender;