CREATE ROLE tolia WITH LOGIN PASSWORD '123456';
GRANT CONNECT ON DATABASE fatbluefish TO tolia;
GRANT ALL PRIVILEGES ON DATABASE fatbluefish TO tolia;
GRANT CREATE ON TABLESPACE ts_gje71 TO tolia;
GRANT CREATE ON TABLESPACE ts_xca33 TO tolia;
